version: "3.7"

networks:
  vaccination:

services:
  # redis:
  #   image: redis:5-alpine
  #   container_name: vaccination_redis
  #   command: redis-server
  #   networks:
  #     - vaccination
  #   ports:
  #     - 6379:6379
  # esearch:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile_ES
  #   container_name: vaccination_esearch
  #   environment:
  #     discovery.type: single-node
  #     ES_JAVA_OPTS: -Xms512m -Xmx512m
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   networks:
  #     - vaccination
  mysql:
    image: mysql:5.7.28
    restart: always
    container_name: vaccination_db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3307:3306
    networks:
      - vaccination
  # sidekiq: &sidekiq
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: vaccination_sidekiq
  #   volumes:
  #     - .:/app
  #     - '/app/tmp'
  #   networks:
  #     - vaccination
  #   depends_on:
  #     - redis
  #     - mysql
  #   command: bundle exec sidekiq
  #   environment:
  #     DB_SERVERNAME: mysql
  #     REDIS_SERVERNAME: redis://redis:6379/1
  #     ELASTICSEARCH_URL: http://esearch:9200
  #     RAILS_ENV: development
  #     DISABLE_SPRING: 'true'
  web:
    # <<: *sidekiq
    build: .
    container_name: vaccination_web
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
    command: rails s -b 0.0.0.0
    networks:
      - vaccination
    ports:
      - 4000:3000
    env_file: .env
    restart: always
    depends_on:
      - mysql

volumes:
  mysql-data:
