version: "3.7"
services:
  redis:
    image: redis:5.0.6-alpine3.10
    volumes:
      - redis-data:/data
    restart: always
  mysql:
    image: mysql:5.7.28
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 3307:3306
  web:
    build: .
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
    command: rails s -b 0.0.0.0
    ports:
      - 4000:3000
    tty: true
    stdin_open: true
    env_file: .env
    restart: always
    depends_on:
      - mysql
      - redis
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
volumes:
  mysql-data:
  redis-data:
