version: '3.7'
services:
  mysql:
    image: mysql:5.7.28
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  web:
    build: .
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/tmp/pids/
    command: rails s -b 0.0.0.0
    ports:
      - 4000:3000
    tty: true
    stdin_open: true
    env_file: .env
    restart: always
    depends_on:
      - mysql

volumes:
  mysql-data:
