default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  host: mysql
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: vaccinenation_management

test:
  <<: *default
  database: vaccinenation_management_test

production:
  <<: *default
  database: vaccinenation_management_production
