default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
  host: mysql

development:
  <<: *default
  database: vaccinenation_management

test:
  <<: *default
  database: vaccinenation_management_test

production:
  <<: *default
  database: vaccinenation_management_production
