default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 1
  host: localhost

development:
  <<: *default
  database: vaccinenation_management

test:
  <<: *default
  database: vaccinenation_management_test

production:
  <<: *default
  database: vaccinenation_management_production
