active_record:
  details_info:
    name:
      minimum: 1
      maximum: 50
    number_phone:
      minimum: 6
      maximum: 30
    email:
      regex: !ruby/regexp '/\A([\w+\-]+(\.[\w+\-]+)*|[\w+\-]+)@(\.?[a-z\d\-]+)+\z/'
  info_injection_book:
    name:
      minimum: 0
      maximum: 50
    number_phone:
      minimum: 6
      maximum: 30
    regex:
      email: !ruby/regexp '/\A([\w+\-]+(\.[\w+\-]+)*|[\w+\-]+)@(\.?[a-z\d\-]+)+\z/'
      number_phone: !ruby/regexp '/\A\+?(\s*\d\s*-?\.?)+\z/'
      password: !ruby/regexp '/\A[a-zA-Z0-9@%+\\\/''!#\$\^\?:,\(\)\{\}\[\]`\~\-_\=\.]{8,16}\z/'
      identify: !ruby/regexp '/\A\+?(\s*\d\s*-?\.?)+\z/'
  injection_book:
    name:
      minimum: 0
      maximum: 50
  account:
    role:
      admin: 1
      super_admin: 2
      user: 3
      staff: 4
      doctor: 5
      nurse: 6
